### ISSUE TITLE
Support for Firefox Quantum Extended Support Release

### ISSUE THREAD

**Issue by gesobak** [pmario/file-backups#26] opened 2018-09-20 16:35 UTC
I tried to install the Add-on in  Firefox Quantum Extended Support Release 60.2.0esr (32-Bit).
The website
https://addons.mozilla.org/de/firefox/addon/file-backups/?src=search
complained that the Add-on is not compatible.
I installed via downloaded file and it works fine. Probably some version compare needs to be adjusted.
It would be nice, if this gets fixed.
Thanks!

**Comment by pmario** [comment] 2018-09-21 07:15
I'll have a closer look. Thx for the info

**Comment by pmario** [comment] 2018-09-21 07:16
Which OS do you use

**Comment by gesobak** [comment] 2018-09-21 15:54
It is my Laptop at work which runs Win10.
If you need more details, I can check next week.
Maybe the browser is specially adapted by the companys IT department, which rolls this out.

**Comment by pmario** [comment] 2018-09-21 19:45
I'll have a look. At the moment I'm using linux. On Tuesday I'll have win 10 again :)

**Comment by gesobak** [comment] 2018-09-26 17:45
You would do me really a favour. Right now I have to install the plugin after each new login, so to say once a day. The plugin gets kicked out, probably due to the IT departments policy.

**Comment by pmario** [comment] 2018-09-28 14:54
I needed to create a VM to install the ESR version. ... The problem is, it works as expected. ... BUT I'm using a 64 bit version. I'll try it again with ESR 32 bit if possible

**Comment by pmario** [comment] 2018-09-28 14:59
Did install FF 32 V 60.2.1esr (32bit) It doesn't show an incompatibility warning. ... May be your IT needs to whitelist FF AddOns??

**Comment by pmario** [comment] 2018-09-28 15:07
see: https://github.com/mozilla/policy-templates/blob/master/README.md#extensions-machine-only

**Comment by pmario** [comment] 2018-09-28 15:08
or: https://github.com/mozilla/policy-templates/blob/master/README.md#installaddonspermission

**Comment by gesobak** [comment] 2018-10-02 11:33
Thanks for your help, the above links on the policy file and your time spent checking!
Sorry for opening this as a bug. For me it is OK, if you close this bug as invalid.
I'll try to check that policy file before getting into contact with the IT department.
It should be possible to find it in the file system.

**Comment by pmario** [comment] 2018-10-02 23:10
OK. I'll leave it open. You can close it, when you have the info. Let me know how it worked out if thats possible.

**Comment by gesobak** [comment] 2018-10-04 10:00
Checked the file "policies.json". Content:
```
{
  "policies": {
     "DisableAppUpdate": true,
	 "DisableFirefoxAccounts": true,
	 "DisableFormHistory": true,
	 "EnableTrackingProtection": {
		"Value": true,
		"Locked": false
		},
	"NoDefaultBookmarks": true,
	"RememberPasswords": false,
	"DisableMasterPasswordCreation": true,
	"DisableFirefoxStudies": true,
	"DisableProfileRefresh": true,
	"DisableTelemetry": true,
	"OfferToSaveLogins": false,
	"SearchBar": "separate",
	"Certificates": {
      "ImportEnterpriseRoots": true
    }
	}
}
```
There is no entry for "Extensions (Machine only)" or "InstallAddonsPermission".
I have no clue how to check Group Policy settings.

**Comment by gesobak** [comment] 2018-10-11 18:31
FYI: I raised a ticket at IT.

As a standard behaviour at first level support they deleted Cookies, Site Data and Cached Site Data completely. To my surprise this seemed to work. I could reboot, log off and on and the Add-on was still installed. So I closed the ticket.

Today working from home the Add-on was gone again (strange). I'll further test, check and might raise the ticket again.

I have no idea why deleting data in firefox at least temporarily solved the problem.

**Comment by gesobak** [comment] 2018-10-11 18:36
I forgot to mention: The problem with the incompatibilty message vanised. I do not know why. Maybe through an update of firefox. No I could install the Add-on via the regular way, but it vanished from firefox after reboot or log off/log on.

**Comment by pmario** [comment] 2018-10-11 18:36
That's strange

**Closed as completed** 2019-08-27 20:04 UTC
